{% set name = "sagemaker-kernel-wrapper" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6986e03c4c9117ddf9911da913f511ebaa3d4f2258848e4717852f0510ca5ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - boto3

test:
  imports:
    - sagemaker_kernel_wrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Kernel Wrapper Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nileshvd
    - just4brown
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
